import type { CaseData, ScreeningResult, UnderwritingResult, CreditNarrative } from './types'

export const mockScreeningResult: ScreeningResult = {
  overallScore: 78,
  confidenceScore: 85,
  recommendation: 'proceed',
  reasoning: 'The prospect shows strong fundamentals with verified company registration, clean director records, and consistent business operations. Industry is within risk appetite with stable outlook. Minor probe required for existing banking exposure levels.',
  checks: [
    { id: '1', dimension: 'Company Legitimacy', category: 'companyLegitimacy', check: 'Company Registration Status', dataSource: 'SSM/ROC Registry', status: 'clear', finding: 'Active Sdn Bhd since 2018', confidence: 95 },
    { id: '2', dimension: 'Company Legitimacy', category: 'companyLegitimacy', check: 'Business Operating Presence', dataSource: 'Google Maps / Website', status: 'clear', finding: 'Physical presence verified at Jalan Ampang', confidence: 90 },
    { id: '3', dimension: 'Company Legitimacy', category: 'companyLegitimacy', check: 'Business Activity Consistency', dataSource: 'SSM Business Code', status: 'clear', finding: 'Consistent with declared manufacturing activity', confidence: 88 },
    { id: '4', dimension: 'Company Legitimacy', category: 'companyLegitimacy', check: 'Business Age', dataSource: 'SSM Incorporation Date', status: 'clear', finding: '6 years of operation', confidence: 100 },
    { id: '5', dimension: 'Company Legitimacy', category: 'companyLegitimacy', check: 'Paid-up Capital', dataSource: 'SSM Records', status: 'clear', finding: 'RM500,000 paid-up capital', confidence: 100 },
    { id: '6', dimension: 'Director Risk', category: 'directorRisk', check: 'Director Bankruptcy', dataSource: 'Insolvency Dept / CTOS', status: 'clear', finding: 'No bankruptcy records', confidence: 98 },
    { id: '7', dimension: 'Director Risk', category: 'directorRisk', check: 'Director Litigation', dataSource: 'Court Records / CTOS', status: 'clear', finding: 'No pending litigation', confidence: 95 },
    { id: '8', dimension: 'Director Risk', category: 'directorRisk', check: 'Director Business History', dataSource: 'SSM Directorship Network', status: 'clear', finding: 'Stable history with 2 active companies', confidence: 88 },
    { id: '9', dimension: 'Director Risk', category: 'directorRisk', check: 'Director AML Risk', dataSource: 'Sanctions / PEP Database', status: 'clear', finding: 'No sanctions or PEP exposure', confidence: 99 },
    { id: '10', dimension: 'Industry Risk', category: 'industryRisk', check: 'Industry Within Risk Appetite', dataSource: 'Internal Credit Policy', status: 'clear', finding: 'Manufacturing - Acceptable industry', confidence: 95 },
    { id: '11', dimension: 'Industry Risk', category: 'industryRisk', check: 'Industry Economic Outlook', dataSource: 'Industry Reports / BNM', status: 'clear', finding: 'Stable sector with moderate growth', confidence: 82 },
    { id: '12', dimension: 'Industry Risk', category: 'industryRisk', check: 'Regulatory Risk', dataSource: 'Sector Licensing', status: 'clear', finding: 'Licensed manufacturing facility', confidence: 100 },
    { id: '13', dimension: 'Credit Signals', category: 'creditSignals', check: 'Credit Bureau Score', dataSource: 'CTOS / CCRIS', status: 'clear', finding: 'CTOS Score: 720 - Good standing', confidence: 95 },
    { id: '14', dimension: 'Credit Signals', category: 'creditSignals', check: 'Existing Banking Exposure', dataSource: 'CCRIS', status: 'probe', finding: 'Moderate leverage - RM2.5M existing facilities', confidence: 75 },
    { id: '15', dimension: 'Credit Signals', category: 'creditSignals', check: 'Trade Payment Behaviour', dataSource: 'CTOS Trade References', status: 'clear', finding: 'Good payment history', confidence: 88 },
    { id: '16', dimension: 'Business Viability', category: 'businessViability', check: 'Turnover vs Loan Size', dataSource: 'RM Input + AI Benchmark', status: 'clear', finding: 'Loan is 25% of annual revenue - Reasonable', confidence: 85 },
    { id: '17', dimension: 'Business Viability', category: 'businessViability', check: 'Business Model Clarity', dataSource: 'RM Interview + AI', status: 'clear', finding: 'Clear B2B manufacturing model', confidence: 90 },
    { id: '18', dimension: 'Business Viability', category: 'businessViability', check: 'Customer Concentration', dataSource: 'RM Input', status: 'probe', finding: 'Top 3 customers = 60% revenue', confidence: 70 },
    { id: '19', dimension: 'Operational Indicators', category: 'operationalIndicators', check: 'Premise Legitimacy', dataSource: 'Google Street View', status: 'clear', finding: 'Appropriate industrial facility', confidence: 92 },
    { id: '20', dimension: 'Fraud Signals', category: 'fraudSignals', check: 'Synthetic Identity Indicators', dataSource: 'Fraud Databases', status: 'clear', finding: 'Identity verified', confidence: 98 },
  ],
  dimensions: {
    companyLegitimacy: { score: 92, status: 'low', findings: ['Active company since 2018', 'Physical presence verified', 'RM500,000 paid-up capital'] },
    directorRisk: { score: 95, status: 'low', findings: ['No bankruptcy records', 'Clean litigation history', 'No AML/sanctions exposure'] },
    industryRisk: { score: 85, status: 'low', findings: ['Manufacturing within risk appetite', 'Stable sector outlook', 'Licensed operations'] },
    creditSignals: { score: 72, status: 'medium', findings: ['Good CTOS score of 720', 'Moderate existing leverage', 'Good trade payment history'] },
    businessViability: { score: 78, status: 'medium', findings: ['Reasonable loan-to-revenue ratio', 'Clear business model', 'Some customer concentration'] },
    operationalIndicators: { score: 88, status: 'low', findings: ['Appropriate industrial facility', 'Consistent staff-to-revenue ratio'] },
    fraudSignals: { score: 98, status: 'low', findings: ['Identity verified', 'No suspicious patterns detected'] },
  },
}

export const mockUnderwritingResult: UnderwritingResult = {
  overallScore: 75,
  confidenceScore: 88,
  recommendation: 'proceed',
  financialRatios: {
    grossProfitMargin: [28.5, 30.2, 32.1],
    netProfitMargin: [8.2, 9.5, 10.8],
    debtToEquity: [1.8, 1.5, 1.2],
    currentRatio: [1.4, 1.6, 1.8],
    dscr: [1.25, 1.35, 1.45],
    debtToEbitda: [3.2, 2.8, 2.4],
    years: ['FY2022', 'FY2023', 'FY2024'],
  },
  categories: [
    {
      name: 'Financial Strength',
      status: 'low',
      score: 82,
      explanation: 'The company demonstrates improving financial health with positive equity, growing profitability, and strengthening capital adequacy over the past three years.',
      checks: [
        { name: 'Revenue Trend', status: 'clear', value: '+12% CAGR', benchmark: '>5% growth' },
        { name: 'Profitability', status: 'clear', value: '10.8% NPM', benchmark: '>5% NPM' },
        { name: 'Net Worth', status: 'clear', value: 'RM2.8M positive', benchmark: 'Positive equity' },
        { name: 'Capital Adequacy', status: 'clear', value: 'D/E 1.2x', benchmark: '<2.0x' },
      ],
    },
    {
      name: 'Cashflow & Repayment Capacity',
      status: 'medium',
      score: 72,
      explanation: 'Operating cashflow is stable with DSCR above 1.3x, indicating adequate capacity to service new debt. Some seasonality noted in Q4 operations.',
      checks: [
        { name: 'DSCR', status: 'clear', value: '1.45x', benchmark: '>1.2x' },
        { name: 'Operating Cashflow', status: 'clear', value: 'RM1.2M positive', benchmark: 'Positive' },
        { name: 'Cash Conversion Cycle', status: 'probe', value: '85 days', benchmark: '<60 days' },
        { name: 'Bank Statement Consistency', status: 'clear', value: 'Consistent', benchmark: 'Match with revenue' },
      ],
    },
    {
      name: 'Borrower Behaviour',
      status: 'low',
      score: 88,
      explanation: 'Clean CCRIS repayment history with no overdue accounts. Banking conduct is satisfactory with minimal bounced payments.',
      checks: [
        { name: 'CCRIS Repayment', status: 'clear', value: 'No overdue', benchmark: 'Clean' },
        { name: 'CTOS Legal Records', status: 'clear', value: 'No litigation', benchmark: 'Clean' },
        { name: 'Banking Conduct', status: 'clear', value: 'Clean', benchmark: 'No bounced payments' },
        { name: 'Tax Compliance', status: 'clear', value: 'Compliant', benchmark: 'Filed on time' },
      ],
    },
    {
      name: 'Debt Burden & Exposure',
      status: 'medium',
      score: 68,
      explanation: 'Total banking exposure is manageable at RM2.5M with existing facilities. Debt-to-EBITDA of 2.4x is within acceptable range but requires monitoring.',
      checks: [
        { name: 'Total Bank Exposure', status: 'clear', value: 'RM2.5M', benchmark: '<RM5M' },
        { name: 'Debt-to-EBITDA', status: 'clear', value: '2.4x', benchmark: '<3x' },
        { name: 'Cross-Bank Obligations', status: 'probe', value: '2 banks', benchmark: '<3 banks' },
        { name: 'Guarantee Obligations', status: 'clear', value: 'RM500K', benchmark: 'Minimal' },
      ],
    },
    {
      name: 'Revenue Quality',
      status: 'medium',
      score: 70,
      explanation: 'Revenue is primarily from B2B contracts with moderate customer concentration. Top 3 customers account for 60% of revenue which presents some risk.',
      checks: [
        { name: 'Customer Concentration', status: 'probe', value: '60% top 3', benchmark: '<40%' },
        { name: 'Contract Stability', status: 'clear', value: '2-year contracts', benchmark: 'Long term' },
        { name: 'Revenue Legitimacy', status: 'clear', value: 'Verified sales', benchmark: 'Genuine' },
        { name: 'Industry Demand', status: 'clear', value: 'Growing', benchmark: 'Stable/Growing' },
      ],
    },
    {
      name: 'Operational Viability',
      status: 'low',
      score: 85,
      explanation: 'Business operations are well-established with appropriate capacity to support current and projected revenue. Management team has relevant industry experience.',
      checks: [
        { name: 'Business Capacity', status: 'clear', value: 'Operational', benchmark: 'Adequate' },
        { name: 'Inventory Turnover', status: 'clear', value: '6x annually', benchmark: '>4x' },
        { name: 'Asset Utilisation', status: 'clear', value: '78%', benchmark: '>70%' },
        { name: 'Management Capability', status: 'clear', value: 'Competent', benchmark: 'Experienced' },
      ],
    },
  ],
  revenueData: [
    { year: 'FY2020', revenue: 6200000, profit: 430000 },
    { year: 'FY2021', revenue: 6800000, profit: 510000 },
    { year: 'FY2022', revenue: 7500000, profit: 615000 },
    { year: 'FY2023', revenue: 8200000, profit: 779000 },
    { year: 'FY2024', revenue: 9100000, profit: 982000 },
  ],
  debtData: [
    { year: 'FY2022', debt: 4500000, equity: 2500000 },
    { year: 'FY2023', debt: 4000000, equity: 2650000 },
    { year: 'FY2024', debt: 3400000, equity: 2800000 },
  ],
}

export const mockCreditNarrative: CreditNarrative = {
  businessProfile: {
    background: 'Precision Manufacturing Sdn Bhd ("the Company") was incorporated in 2018 and is primarily engaged in the manufacturing of precision metal components for the automotive and electronics industries. The Company operates from a 15,000 sq ft facility in the Puchong Industrial Area and employs 45 full-time staff. The founder and Managing Director, Mr. Ahmad bin Hassan, has over 20 years of experience in precision manufacturing, having previously held senior positions at multinational manufacturing companies.',
    industryContext: 'The precision manufacturing sector in Malaysia has shown resilient growth, supported by the ongoing semiconductor boom and automotive industry recovery. Industry reports indicate a compound annual growth rate of 8-10% over the next five years, driven by increasing demand for high-precision components in electric vehicles and consumer electronics. The Company is well-positioned to benefit from these trends given its established capabilities and existing customer relationships with Tier 1 suppliers.',
    businessModel: 'The Company operates a B2B model, manufacturing precision components to order for a portfolio of established customers. Key customers include automotive parts suppliers and electronics manufacturers. The production process involves CNC machining, metal stamping, and quality assurance testing. Revenue is generated through a combination of long-term supply agreements (60%) and spot orders (40%), providing both stability and flexibility.',
  },
  financialAssessment: {
    revenueTrends: 'Revenue has grown consistently over the past five years, achieving a CAGR of 12% from RM6.2M in FY2020 to RM9.1M in FY2024. This growth has been driven by expanding relationships with existing customers and the acquisition of new accounts in the electronics sector. Management projects revenue to reach RM10.5M in FY2025, supported by recently signed contracts with two new automotive customers.',
    profitabilityAnalysis: 'The Company has demonstrated improving profitability with gross profit margin expanding from 28.5% in FY2022 to 32.1% in FY2024. This improvement reflects operational efficiencies, better capacity utilization, and favorable raw material pricing. Net profit margin has similarly improved from 8.2% to 10.8% over the same period. The Company maintains a lean cost structure with SG&A expenses at approximately 18% of revenue.',
    repaymentCapacity: 'Based on FY2024 financial performance, the Company generates annual operating cashflow of approximately RM1.2M. With the proposed facility of RM2.5M over 5 years, the estimated annual debt service would be approximately RM600K. This results in a debt service coverage ratio of 1.45x, comfortably above the minimum threshold of 1.2x. The Company also maintains cash reserves of RM850K as additional buffer.',
  },
  riskAssessment: {
    keyRisks: [
      'Customer Concentration: Top 3 customers account for 60% of revenue, creating dependency risk if any major customer reduces orders',
      'Raw Material Price Volatility: Steel and aluminum prices are subject to global market fluctuations which could impact margins',
      'Currency Exposure: Approximately 30% of raw materials are imported, exposing the Company to MYR/USD exchange rate risk',
      'Key Man Risk: Operations are significantly dependent on the founder/MD and a small senior management team',
    ],
    mitigants: [
      'Customer Diversification: The Company is actively pursuing new customers in different sectors, targeting to reduce top 3 concentration to below 50% within 18 months',
      'Pricing Mechanisms: Supply agreements include quarterly price adjustment clauses tied to commodity indices',
      'Natural Hedge: Approximately 25% of revenue is USD-denominated, providing partial offset to import costs',
      'Management Succession: The Company has recently hired a Deputy GM with 15 years industry experience as part of succession planning',
    ],
  },
  facilityStructure: {
    recommendedAmount: 2500000,
    tenure: '5 years with 6-month grace period',
    collateral: 'First legal charge over industrial property (valued at RM3.8M) with collateral coverage of 152%',
    guarantees: 'Personal guarantee from Mr. Ahmad bin Hassan (MD) covering 100% of facility amount',
  },
  recommendation: 'approve-conditions',
  confidenceScore: 82,
  reasoning: 'The Company demonstrates solid fundamentals with improving financial performance, clean credit history, and viable business operations. While customer concentration presents moderate risk, the Company has concrete plans for diversification. The proposed facility is adequately supported by cashflow (DSCR 1.45x) and secured against valuable industrial property. Approval is recommended subject to achieving customer diversification milestones and quarterly financial reporting covenants.',
}

export const mockCaseData: CaseData = {
  id: 'CASE-2024-00142',
  prospect: {
    id: 'PROS-001',
    companyName: 'Precision Manufacturing Sdn Bhd',
    registrationNumber: '201801012345',
    industry: 'Manufacturing - Metal Components',
    yearsOfOperation: 6,
    estimatedTurnover: 9100000,
    financingPurpose: 'Working Capital & Equipment Purchase',
    requestedLoanAmount: 2500000,
    directorName: 'Ahmad bin Hassan',
    createdAt: new Date('2024-01-15'),
  },
  currentStage: 'narrative',
  screeningResult: mockScreeningResult,
  underwritingResult: mockUnderwritingResult,
  creditNarrative: mockCreditNarrative,
  documents: [
    { id: 'DOC-001', name: 'Audited Financial Statements FY2024.pdf', type: 'Financial Statement', uploadedAt: new Date('2024-01-16') },
    { id: 'DOC-002', name: 'Audited Financial Statements FY2023.pdf', type: 'Financial Statement', uploadedAt: new Date('2024-01-16') },
    { id: 'DOC-003', name: 'Bank Statements - Maybank (6 months).pdf', type: 'Bank Statement', uploadedAt: new Date('2024-01-17') },
    { id: 'DOC-004', name: 'CCRIS Report.pdf', type: 'Bureau Report', uploadedAt: new Date('2024-01-17') },
    { id: 'DOC-005', name: 'CTOS Report.pdf', type: 'Bureau Report', uploadedAt: new Date('2024-01-17') },
    { id: 'DOC-006', name: 'SSM Company Profile.pdf', type: 'Company Document', uploadedAt: new Date('2024-01-15') },
  ],
  timeline: [
    { id: 'TL-001', action: 'Case created - Prospect information entered', timestamp: new Date('2024-01-15T09:00:00'), user: 'Sarah Tan (RM)' },
    { id: 'TL-002', action: 'AI Rapid Screening completed', timestamp: new Date('2024-01-15T09:05:00'), user: 'System' },
    { id: 'TL-003', action: 'Decision: Proceed to Underwriting', timestamp: new Date('2024-01-15T09:15:00'), user: 'Sarah Tan (RM)' },
    { id: 'TL-004', action: 'Financial documents uploaded', timestamp: new Date('2024-01-16T14:30:00'), user: 'Sarah Tan (RM)' },
    { id: 'TL-005', action: 'Bureau reports uploaded', timestamp: new Date('2024-01-17T10:00:00'), user: 'Sarah Tan (RM)' },
    { id: 'TL-006', action: 'AI Financial Analysis completed', timestamp: new Date('2024-01-17T10:15:00'), user: 'System' },
    { id: 'TL-007', action: 'Site visit conducted', timestamp: new Date('2024-01-18T11:00:00'), user: 'Sarah Tan (RM)' },
    { id: 'TL-008', action: 'Decision: Proceed to Credit Narrative', timestamp: new Date('2024-01-18T15:00:00'), user: 'Sarah Tan (RM)' },
    { id: 'TL-009', action: 'AI Credit Narrative generated', timestamp: new Date('2024-01-18T15:05:00'), user: 'System' },
  ],
  overallRiskScore: 75,
}
